"""Train a tiny logistic-regression safety model and export it for ESP32.

CSV columns:
ax, ay, az, gx, gy, gz, humidity, mq135, label
label: 0 = SAFE, 1 = DANGER

Run:
    python train_mine_safety_ai.py sample_sensor_data.csv

It creates ai_model.h in the same folder.
"""
import sys
from pathlib import Path
import numpy as np
import pandas as pd

FEATURES = ["ax", "ay", "az", "gx", "gy", "gz", "humidity", "mq135"]


def sigmoid(z):
    z = np.clip(z, -50, 50)
    return 1.0 / (1.0 + np.exp(-z))


def train_logistic(X, y, lr=0.03, epochs=5000, l2=0.001):
    w = np.zeros(X.shape[1], dtype=np.float64)
    b = 0.0
    n = len(X)
    for _ in range(epochs):
        p = sigmoid(X @ w + b)
        err = p - y
        w -= lr * ((X.T @ err) / n + l2 * w)
        b -= lr * err.mean()
    return w, b


def main():
    if len(sys.argv) != 2:
        print("Usage: python train_mine_safety_ai.py sensor_data.csv")
        sys.exit(1)

    csv_path = Path(sys.argv[1])
    df = pd.read_csv(csv_path)
    needed = FEATURES + ["label"]
    missing = [c for c in needed if c not in df.columns]
    if missing:
        raise ValueError("Missing columns: " + ", ".join(missing))

    df = df[needed].dropna()
    X = df[FEATURES].astype(float).to_numpy()
    y = df["label"].astype(int).to_numpy()
    if set(np.unique(y)) != {0, 1}:
        raise ValueError("Training CSV must contain both labels 0 (SAFE) and 1 (DANGER).")

    mean = X.mean(axis=0)
    std = X.std(axis=0)
    std[std < 1e-9] = 1.0
    Xs = (X - mean) / std

    w, b = train_logistic(Xs, y)
    p = sigmoid(Xs @ w + b)
    pred = (p >= 0.5).astype(int)
    acc = float((pred == y).mean())

    out = csv_path.parent / "ai_model.h"
    text = "// Automatically generated by train_mine_safety_ai.py\n#pragma once\n\n"
    text += "const int AI_FEATURES = 8;\n\n"
    text += "const float AI_MEAN[AI_FEATURES] = {" + ", ".join(f"{v:.9g}f" for v in mean) + "};\n"
    text += "const float AI_STD[AI_FEATURES] = {" + ", ".join(f"{v:.9g}f" for v in std) + "};\n"
    text += "const float AI_W[AI_FEATURES] = {" + ", ".join(f"{v:.9g}f" for v in w) + "};\n"
    text += f"const float AI_BIAS = {b:.9g}f;\n"
    text += f"// Training accuracy on supplied data: {acc*100:.2f}%\n"
    out.write_text(text, encoding="utf-8")

    print(f"Samples: {len(df)}")
    print(f"Training accuracy: {acc*100:.2f}%")
    print(f"Created: {out}")


if __name__ == "__main__":
    main()
